version: '2.3'

services:

  blender:
    image: cloudnativecomputer/blender:latest
    shm_size: 6gb
    runtime: nvidia
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:blender.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    volumes:
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE

volumes:
  CLOUD_COMPUTER_HOME:
  CLOUD_COMPUTER_CLOUDSTORAGE:
