version: '3.5'

services:

  gnumeric:
    image: cloudnativecomputer/gnumeric:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:gnumeric.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    volumes:
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE

volumes:
  CLOUD_COMPUTER_HOME:
  CLOUD_COMPUTER_CLOUDSTORAGE:
