version: '3.5'

services:

  notion:
    image: cloudnativecomputer/notion:latest
    shm_size: 6gb
    restart: always
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:notion.$CLOUD_COMPUTER_HOST_DNS
      - traefik.port=8080
    volumes:
      - CLOUD_COMPUTER_HOME:$CLOUD_COMPUTER_HOME
      - CLOUD_COMPUTER_CLOUDSTORAGE:$CLOUD_COMPUTER_CLOUDSTORAGE

volumes:
  CLOUD_COMPUTER_HOME:
  CLOUD_COMPUTER_CLOUDSTORAGE:
